# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dd1f0222cfaa3481f29f880ffc595bcc0279a79fba86011ec80a5a15f2d6aa08eadd97ed52f62c837d30ad8fb9ee70f8ea93365afaa6e57be6059c9d5678723

test:
  secret_key_base: d59b852235d84f46813c31c55c0c619eed60b43310af26296fedee4a811ff0bf53106080a84c72c834c3a752fa9a9a7abe0dc3777f7aad55ffe5aa6770c0542e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
